- name: get the repo
  git: repo=https://github.com/zalando/postgres-operator.git dest=/root/zalando-postgres-operator version=551564011139d5a6cb9f635d091b2b54f56f125d

- name: apply manifests/configmap.yaml
  command: kubectl apply -f /root/zalando-postgres-operator/manifests/configmap.yaml

- name: apply manifests/operator-service-account-rbac.yaml
  command: kubectl apply -f /root/zalando-postgres-operator/manifests/operator-service-account-rbac.yaml

- name: apply manifests/postgres-operator.yaml
  shell: 'sed -e "s#image: registry.opensource.zalan.do/acid/postgres-operator:v1.2.0#image: registry.opensource.zalan.do/acid/postgres-operator:v1.2.0-15-gbb855fd-dirty#g" manifests/postgres-operator.yaml | kubectl apply -f -'
